<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>wpf_poc_host</AssemblyName>
    <OutputPath>D:\Project\The-Great-Sage\bin\build_temp\</OutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="wpf_poc_host.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Web.WebView2.Wpf">
      <HintPath>Microsoft.Web.WebView2.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>Microsoft.Web.WebView2.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>